export const formDefaultValues = {
  oneWayTrip: true,
  origin: "Skardu",
  destination: "Islamabad",
  journeyDate: "12/12/12",
  returnDate: "10/10/10",
  number_of_adults: 1,
  number_of_children: 0,
  number_of_infants: 0,
  adults: [
    {
      firstName: "test",
      surname: "test",
      date_of_birth: "12/12/12",
      phoneNumber: "+92test12344",
      gender: "male",
    },
  ],
  children: [
    {
      firstName: "test",
      surname: "test",
      date_of_birth: "12/12/12",
      gender: "male",
    },
  ],
  infants: [
    {
      firstName: "test",
      surname: "test",
      date_of_birth: "12/12/12",
      gender: "male",
      age: 2,
    },
  ],
  airline: "PIA",
  cabin: "Economy",
  adultFare: 10000,
  childFare: 1000,
  infantFare: 100,
  taxes: 10,
  salesCommission: 10,
  discount: 2,
  gender: "male",
  firstName: "test",
  surName: "test",
  date_of_birth: "10/10/10",
  email: "test@gmail.com",
  phone: "+92 35555071004",
  pnrNumber: "99999",
  ticket: "ticket number is one",
  issueBy: "test",
  ledger: "idk",
  code: "1000",
  grandTotal: 0,
};
